---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
          - aptitude
        state: installed
